services:
  playwright-server:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
      args:
        PLAYWRIGHT_VERSION: ${PLAYWRIGHT_VERSION}
    ipc: host
    command: playwright run-server --host=0.0.0.0 --port=3000
    ports:
      - '3000:3000'
