name: CI
on: workflow_call
permissions: {}
jobs:
  generateChangelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          show-progress: false
          fetch-depth: 0 # fetch all reachable commits
          filter: tree:0 # while fetching trees and blobs on-demand

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm
          node-version-file: 'package.json'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Generate changelog
        run: npm run changelog > changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload npm folder
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: changelog
          path: ./changelog.txt
